Lesson3
NukeDancer/geekshop-server pull request #3
Opened 2021-08-19 13:32 UTC by NukeDancer

Lesson3.

2021-08-19 16:48 UTC, Vokler requested changes

2021-08-19 16:48 UTC, Vokler commented on products/views.py
> +               'products': products_list.values(),
Не обязательно использовать `values()`, просто `Product.objects.all()` тоже будет работать.

2021-08-20 10:43 UTC, Vokler commented
А зачем вы пометили комментарий, как "Resolve conversation", если замечание не исправлено?)

2021-08-20 11:04 UTC, NukeDancer commented on products/views.py
> +               'products': products_list.values(),
Никогда не вносил исправления в pull request. пытаюсь разобраться как это сделать

2021-08-20 11:10 UTC, NukeDancer commented on products/views.py
> +               'products': products_list.values(),
запушил коммит с исправлением "fix views"

2021-08-23 09:23 UTC, Vokler approved these changes

2021-08-23 09:23 UTC, merged